### PR TITLE
Updated iOS and Android AdMob SDK, FB Audience Network and InMobi adapter, added new iOS Rewarded Video

### PR DESCRIPTION
**Pull request by Astrovic**
**Android:**
[Android v.5.1.0](https://github.com/Astrovic/ti.admob/releases/tag/android-5.1.0) - 25 Feb 2022
- Update Google Mobile Ads SDK 20.5.0
- Update Audience Network SDK 6.+
- Update Facebook Adapter 6.8.0.0
- Update InMobi SDK 10.0.1
- Update InMobiAdapter 10.0.1.0

**iOS:**
[iOS v.6.1.0](https://github.com/Astrovic/ti.admob/releases/tag/ios-6.1.0) - 11 May 2023
- Migration to SDK v10
- Update Google Mobile Ads SDK 10.4.0
- Update Audience Network SDK 6.12.0 
- Added Meta Adapter 6.12.0.1
- Removed Facebook Adapter
- Update InMobi SDK 10.5.4
- Update InMobiAdapter 10.5.4.0
- Removed `Admob.setLocation()` because `setLocationWithLatitude` has been removed by Google
- Removed `Admob.showMediationTestSuite()`. You can use `gmamts.showMediationTestSuite()` with the module https://github.com/Astrovic/ti.gmamts.
- Module includes Ad Inspector (https://developers.google.com/admob/ios/ad-inspector). Since the iOS Google Mobile Ads SDK 10 it is possible to test each adUnit by requesting a Request test ad, so you don't need to use MediationTestSuite
- Removed `PersonalizedAdConsent` framework because deprecated by Google 

Both versions are tested and in production on the stores.
Sample app: https://github.com/Astrovic/ti.admob-sample-app

### CODE REVIEW

**Comment by dlewis23** [comment]
The 4.6.0 file linked above gives a 404. It seems like it should go to here: https://github.com/Astrovic/ti.admob/releases/tag/ios-4.5.6

Is this the version I should try out?

**Comment by Astrovic** [comment]
@dlewis23 yes, the last version is 4.6.0 and correct link is https://github.com/Astrovic/ti.admob/releases/tag/ios-4.5.6

**Comment by dlewis23** [comment]
I tried to use this updated 4.6.0 Version today on iOS with TI SDK 10.1.0 GA and it does not work. When I go to build the app I just get the basic error message below. If I change the Admob module version back to 3.0.0 it builds just fine. 

`[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld /Users/donovanlewis/Documents/Appcelerator_Studio_Workspace/iPad\ Test/build/iphone/build/Products/Debug-iphonesimulator/iPadTest.app/iPadTest normal (in target 'iPadTest' from project 'iPadTest')
[ERROR] :  (1 failure)`

**Comment by dlewis23** [comment]
Hello, 

I put a trace on this today as I had some more time and this is the error I get. Seems like something with Facebook is missing?

`[TRACE] ld: warning: directory not found for option '-L/Users/donovanlewis/Documents/Appcelerator_Studio_Workspace/Quick/build/iphone/lib'
[TRACE] ld: framework not found FBSDKCoreKit
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld /Users/donovanlewis/Documents/Appcelerator_Studio_Workspace/Quick/build/iphone/build/Products/Debug-iphonesimulator/Quick.app/Quick normal (in target 'Quick' from project 'Quick')
[ERROR] (1 failure)
`

**Comment by Astrovic** [comment]
My module version uses Facebook mediation, so you have to add Facebook module in your `tiapp.xml`

**Comment by dlewis23** [comment]
Do you happen to have a build of the Admob Module with arm64 support enabled for M1 Mac's in the simulator?

**Comment by hansemannn** [comment]
@dlewis23 @Astrovic Would you mind giving me a quick update where we're at here? It is ready for review and working for you guys?

**Comment by Astrovic** [comment]
@hansemannn  The changes in the PR works correctly, I use it in production both on iOS and Android.
However, it would be necessary to change the documentation because over time changes have been made to the methods and properties that are documented only in the notes of the various releases.

@dlewis23 I think the module uses some old framework that does not support M1 yet, unfortunately I have no way of testing

**Comment by hansemannn** [comment]
Okay, I'll check the APIs (vs docs) and check on the arm64 library of the native SDK!

**Comment by dlewis23** [comment]
@Astrovic @hansemannn I tired to update the module with ARM64 support and I get the following message with the frameworks that do not have ARM64 support. 

`[WARN]  The module is using frameworks (MDFInternationalization.framework,MDFTextAccessibility.framework,MaterialComponents.framework,PersonalizedAdConsent.framework) that do not support simulator arm64. Excluding simulator arm64. The app using this module may fail if you're on an arm64 Apple Silicon device.`

**Comment by hansemannn** [comment]
Yeah, all frameworks have to be an .xcframework and include the arm64-maccatalyst slice. Does Google not provide these, yet?

**Comment by dlewis23** [comment]
It says they do in the release notes since version 7.69.0 back at the end of 2020. But this was for version 8.13.0 of the SDK now its change up to 9.5.0 and when I download it now it looks very different. So I'm not 100% sure where to start. 

https://developers.google.com/admob/ios/download

**Comment by hansemannn** [comment]
Okay, so I updated all Admon SDK's to latest and removed the discontinued `PersonalizedAdConsent` framework and it's API's (while leaving an error log why it was removed). Basically now all thats left to migrate to .xcframework's is:
- MaterialComponents.framework
- MDFInternationalization.framework
- MDFTextAccessibility.framework

They all relate to the material components SDK, which I think should not be part of this module. If some ad-service needs it, the best practive would be to make an own "shallow" module with just these modules, so it can be linked to the required ad service if needed. So it would be good to know why it's here and what we can do about it.

**Comment by Astrovic** [comment]
This PR was very old, and in the meantime the other changes made in my fork have been added here.
These Material frameworks have been added in order to use the [AdMob Google Mobile Ads Mediation Test Suite](https://developers.google.com/admob/ios/mediation-test-suite?hl=en) 
But it is not essential, I had already created a module for this: https://github.com/Astrovic/ti.gmamts
So we can remove it and use the separate module if necessary

**Comment by Astrovic** [comment]
@hansemannn I just released [iOS v.5.0.0](https://github.com/Astrovic/ti.admob/releases/tag/ios-5.0.0) with my last commit [Migration to SDK v9 (9.13.0)](https://github.com/tidev/ti.admob/pull/166/commits/2d8da79083a366687a5360ede4dea966ef62785c)
All old frameworks have been removed, now the module supports arm64 and x86_64.
I updated the iOS documentation with all methods and properties added or removed.
I provided a new iOS sample file which allows to test the module.
The release has been tested on both device and simulator, and works correctly.
So maybe this PR could finally be accepted after years.

**Comment by dlewis23** [comment]
@Astrovic Amazing news. I am going to try out the new iOS version later today and submit it in an app next week. Great work! Will update if I run into anything.

**Comment by hansemannn** [comment]
Perfect! Let me know if it all works for you guys, then I'll merge and release it :) Great community effort!

**Comment by hansemannn** [comment]
@Astrovic Should we merge this? The changes looked fine for a long time, and as you seem to use it in production for a while, I don't see why we shouldn't.

**Comment by Astrovic** [comment]
@hansemannn  yes it works fine. I'm about to release the new iOS version 6.0.0, using the AdMob SDK 10.4.0. Just a few minutes

**Comment by dlewis23** [comment]
Should we wait for that one since its using the latest SDK before merging?

**Comment by Astrovic** [comment]
As you prefer. In case then I can make a new PR with the new version. I did a test with version 6.0.0 and it seems to work fine, but if someone else wants to test it maybe it's better.

**Comment by dlewis23** [comment]
I can test version 6 week with an app.

**Comment by Astrovic** [comment]
I published the new release, I also updated the first comment https://github.com/tidev/ti.admob/pull/166#issue-786216198 with the links to download the zip file.

There is also a link to the test app so you can quickly test the module (https://github.com/Astrovic/ti.admob-sample-app).

I don't understand why the Check CLA fails since I signed it correctly https://github.com/tidev/organization-docs/blob/main/AUTHORIZED_CONTRIBUTORS.md

**Comment by Astrovic** [comment]
@hansemannn I think this PR can be merged. I'm also using the latest updates in production and it works fine.

**Comment by hansemannn** [comment]
@cb1kenobi @joshualambert The CLA action fails with a type error, can one of you take a look there?

**Comment by cb1kenobi** [comment]
@hansemannn @Astrovic CLA check fixed!

/cc @joshualambert

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
@Astrovic It seem like the builds hangs - can you push one more commit? Unfortunately I cannot merge without the check (no permissions to).

**Comment by Astrovic** [comment]
I've just done it.

**Comment by hansemannn** [comment]
Still stuck, mhhh. So sorry for that. I have no permissions to manually merge this

**Comment by cb1kenobi** [comment]
@hansemannn I can force merge it if you'd like. This PR is way too big for me to review/test, so I'm trusting you. :)

**Comment by hansemannn** [comment]
Yeah I've checked it over time. But still, why does the build action hangs as well? It seems like things break randomly 😅

**Comment by cb1kenobi** [comment]
@hansemannn This repo specifically had a branch protection rule that required an old Jenkins check to pass, of which Jenkins doesn't exist anymore. I removed the branch protection rule from this repo. Other repos may also have a similar Jenkins check. I did my best back in the day to clean up each repo's settings, so I obviously missed this one. Whoops.

**Comment by cb1kenobi** [comment]
@Astrovic nice work on this PR!

**Comment by hansemannn** [comment]
Thanks a lot Chris! Always my last rescue! 😊

**Comment by Astrovic** [comment]
Thanks @cb1kenobi! This was an old PR that has grown over time.

It would also be useful to add the ZIP files in the Releases, which are updated in the first comment of the PR.

The dependabot still generates a lot of PR, but I don't know if it's useful.

**Pull request merged**
